export const braceletMaterialList = [
    'Aliminium',
    'Lizard',
    'Yellow Gold',
    'Bicolor (Gold/Steel)',
    'Shark Skin',
    'Rubber',
    'Crocodile Skin',
    'Plastic',
    'Leather',
    'Platinum',
    'Calf skin',
    'Pink Gold',
    'Red Gold',
    'Satin',
    'Snake Skin',
    'Silver',
    'Silicon',
    'Steel',
    'Ostrich Skin',
    'Textile',
    'Titanium',
    'White Gold',
    ];