export const currencyList = [
    'Australian Dollar (AUD)',
    'Bulgarian Lev (BGN)',
    'Brazilian Real (BRL)',
    'Canadian Dollar (CAD)',
    'Swiss Franc (CHF)',
    'Chinese Yuan (CNY)',
    'Czech Koruna (CZK)',
    'Danish Krone (DKK)',
    'Euro (EUR)',
    'British Pound (GBP)',
    'Hong Kong Dollar (HKD)',
    'Croatian Kuna (HRK)',
    'Hungarian Forint (HUF)',
    'Indonesian Rupiah (IDR)',
    'Israeli New Shekel (ILS)',
    'Indian Rupee (INR)',
    'Icelandic Krona (ISK)',
    'Japanese Yen (JPY)',
    'South Korean Won (KRW)',
    'Mexican Peso (MXN)',
    'Malaysian Ringgit (MYR)',
    'Norwegian Krone (NOK)',
    'New Zealand Dollar (NZD)',
    'Philippine Peso (PHP)',
    'Polish Zloty (PLN)',
    'Romanian Leu (RON)',
    'Russian Ruble (RUB)',
    'Swedish Krona (SEK)',
    'Singapore Dollar (SGD)',
    'Thai Baht (THB)',
    'Turkish Lira (TRY)',
    'US Dollar (USD)',
    'South African Rand (ZAR)',
    'United Arab Emirates Dirham (AED)',
    'Afghan Afghani (AFN)',
    'Albanian Lek (ALL)',
    'Armenian Dram (AMD)',
    'Netherlands Antillean Guilder (ANG)',
    'Angolan Kwanza (AOA)',
    'Argentine Peso (ARS)',
    'Aruban Florin (AWG)',
    'Azerbaijani Manat (AZN)',
    'Bosnia and Herzegovina Convertible Mark (BAM)',
    'Barbadian Dollar (BBD)',
    'Bangladeshi Taka (BDT)',
    'Burundian Franc (BIF)',
    'Bermudian Dollar (BMD)',
    'Brunei Dollar (BND)',
    'Bolivian Boliviano (BOB)',
    'Belize Dollar (BZD)',
    'Congolese Franc (CDF)',
    'Cape Verdean Escudo (CVE)',
    'Costa Rican Colón (CRC)',
    'Cuban Peso (CUP)',
    'Djiboutian Franc (DJF)',
    'Dominican Peso (DOP)',
    'Algerian Dinar (DZD)',
    'Egyptian Pound (EGP)',
    'Eritrean Nakfa (ERN)',
    'Ethiopian Birr (ETB)',
    'Fijian Dollar (FJD)',
    'Falkland Islands Pound (FKP)',
    'Faroe Islands Króna (FOK)',
    'Gibraltar Pound (GIP)',
    'Georgian Lari (GEL)',
    'Guernsey Pound (GGP)',
    'Ghanaian Cedi (GHS)',
    'Gambian Dalasi (GMD)',
    'Guinean Franc (GNF)',
    'Guatemalan Quetzal (GTQ)',
    'Guyanese Dollar (GYD)',
    'Honduran Lempira (HNL)',
    'Haitian Gourde (HTG)',
    'Iraqi Dinar (IQD)',
    'Iranian Rial (IRR)',
    'Jersey Pound (JEP)',
    'Jamaican Dollar (JMD)',
    'Jordanian Dinar (JOD)',
    'Kazakhstani Tenge (KZT)',
    'Kyrgystani Som (KGS)',
    'Cambodian Riel (KHR)',
    'Kiribati Dollar (KID)',
    'Comorian Franc (KMF)',
    'Kuwaiti Dinar (KWD)',
    'Cayman Islands Dollar (KYD)',
    'Lao Kip (LAK)',
    'Lebanese Pound (LBP)',
    'Sri Lankan Rupee (LKR)',
    'Liberian Dollar (LRD)',
    'Lesotho Loti (LSL)',
    'Libyan Dinar (LYD)',
    'Moroccan Dirham (MAD)',
    'Moldovan Leu (MDL)',
    'Malagasy Ariary (MGA)',
    'North Macedonian Denar (MKD)',
    'Myanmar Kyat (MMK)',
    'Mongolian Tugrik (MNT)',
    'Macanese Pataca (MOP)',
    'Mauritanian Ouguiya (MRU)',
    'Mauritian Rupee (MUR)',
    'Maldivian Rufiyaa (MVR)',
    'Malawian Kwacha (MWK)',
    'Nigerian Naira (NGN)',
    'Nicaraguan Córdoba (NIO)',
    'Nepalese Rupee (NPR)',
    'Omani Rial (OMR)',
    'Panamanian Balboa (PAB)',
    'Peruvian Nuevo Sol (PEN)',
    'Papua New Guinean Kina (PGK)',
    'Pakistani Rupee (PKR)',
    'Paraguayan Guarani (PYG)',
    'Qatari Rial (QAR)',
    'Serbian Dinar (RSD)',
    'Rwandan Franc (RWF)',
    'Saudi Riyal (SAR)',
    'Solomon Islands Dollar (SBD)',
    'Seychellois Rupee (SCR)',
    'Sudanese Pound (SDG)',
    'Sierra Leonean Leone (SLE)',
    'Somali Shilling (SOS)',
    'Surinamese Dollar (SRD)',
    'South Sudanese Pound (SSP)',
    'São Tomé and Príncipe Dobra (STN)',
    'Syrian Pound (SYP)',
    'Swazi Lilangeni (SZL)',
    'Tajikistani Somoni (TJS)',
    'Turkmenistani Manat (TMT)',
    'Tunisian Dinar (TND)',
    'Tongan Paʻanga (TOP)',
    'Trinidad and Tobago Dollar (TTD)',
    'New Taiwan Dollar (TWD)',
    'Tanzanian Shilling (TZS)',
    'Ukrainian Hryvnia (UAH)',
    'Ugandan Shilling (UGX)',
    'Uruguayan Peso (UYU)',
    'Uzbekistani Som (UZS)',
    'Venezuelan Bolívar (VES)',
    'Vietnamese Dong (VND)',
    'Vanuatu Vatu (VUV)',
    'Samoan Tala (WST)',
    'Central African CFA Franc (XAF)',
    'East Caribbean Dollar (XCD)',
    'Special Drawing Rights (XDR)',
    'West African CFA Franc (XOF)',
    'CFP Franc (XPF)',
    'Yemeni Rial (YER)',
    'Zambian Kwacha (ZMW)',
    'Zimbabwean Dollar (ZWL)',
]